### ISSUE TITLE
Listening host not respected with Velocity

### ISSUE THREAD

**Issue by mkaag** [weihao/bungeecord-prometheus-exporter#144]
Hi there, 

thank you for your work, the plugin is great, I used to deploy it with Waterfall with great results. I recently switched to Velocity and I'm facing now an issue with the listening host.

Typically the plugin is listening on `127.0.0.1` independently of the `host` defined in the `config.json`. My Prometheus server is running on a different host and I need to expose the exporter to an external IP.

Note that I didn't face this issue with Waterfall. Is there anything I can do on my side to fix this (except moving back to Waterfall)? Also do you need anything particular to diagnose the issue?

Thank you, regards,
Maurice

**Comment by weihao** [comment]
https://github.com/weihao/bungeecord-prometheus-exporter/blob/main/src/main/java/org/akadia/prometheus/velocity/PrometheusVelocityExporter.java#L78

should be respected

**Comment by weihao** [comment]
Added docker compose for testing, this behavior was not observed.

If you could reproduce, let me know and reopen this.
