### ISSUE TITLE
Requires RedisBungee to even work?

### ISSUE THREAD

**Issue by DieselGaming** [weihao/bungeecord-prometheus-exporter#23]
To get the plugin to load on my BungeeCord I had to edit the config.yml to manually disable the supposed "RedisBungee" checks.

However, importing the dashboard to Grafana appears to just make a dashboard with random placeholder like information, and the proxy (BungeeCord) isn't even detected itself. Its running on the default 9225 as shown in this start-up guide, with the correct allocation and assignment, I can go to `serverIP:port/metrics` and that resolves - the dashboard in Grafana does not.

**Comment by DieselGaming** [comment]
I've edited the original comment with my issue.

**Comment by DieselGaming** [comment]
Well from a quick and uneducated look, I believe Grafana uses `bungee_redis_bungee_online_proxies` from `serverIP:port/metrics` to get a list of proxies. But, as I said, I don't use RedisBungee - is RedisBungee actually required? It doesn't say that, and there is no clear indication that RedisBungee is required for the entire thing to even work, plus, any way to disable it.

**Comment by weihao** [comment]
RedisBungee is not required. It was actually removed in the latest version. What error are you seeing?

**Comment by weihao** [comment]
https://github.com/weihao/bungeecord-prometheus-exporter/commit/885d4c10d3f33d3de788bd837d33dab2ed073562


I have updated the dashboard to exclude RedisBungee.

**Comment by DieselGaming** [comment]
The Bukkit/Spigot version appears to work as expected.

*Just updated to your new dashboard*
However, the BungeeCord version's grafana page just loads of random data in place of whats supposed to be there:
<img width="1280" alt="Screenshot 2021-08-18 at 01 15 04" src="https://user-images.githubusercontent.com/44411085/129816800-789e3d2b-27ab-413e-a3b1-25abe097f0ab.png">

**Comment by DieselGaming** [comment]
Another thing to note is on the Bukkit version, the Variable is set to use Prometheus, but on this BungeeCord version it is set to Grafana:

Bukkit:
<img width="777" alt="Screenshot 2021-08-18 at 01 18 42" src="https://user-images.githubusercontent.com/44411085/129817054-fa9c4a6a-caf2-47e5-9be6-0f89dafb1cd2.png">

BungeeCord:
<img width="765" alt="Screenshot 2021-08-18 at 01 19 16" src="https://user-images.githubusercontent.com/44411085/129817107-e49af3d9-273c-468a-a912-2c2d59822b22.png">

Is this intentional? 
*(I'm completely new to Grafama and set up everything to use this :D)*

**Comment by weihao** [comment]
> The Bukkit/Spigot version appears to work as expected.
> 
> _Just updated to your new dashboard_
> However, the BungeeCord version's grafana page just loads of random data in place of whats supposed to be there:
> <img alt="Screenshot 2021-08-18 at 01 15 04" width="1280" src="https://user-images.githubusercontent.com/44411085/129816800-789e3d2b-27ab-413e-a3b1-25abe097f0ab.png">

You need to update prometheus config to 

```
    static_configs:
      - targets: [ 'localhost:9225' ]
        labels:
          proxy_name: 'proxy1'
```

server_name was changed to proxy_name

**Comment by DieselGaming** [comment]
I've changed server_name to proxy_name, and the only difference I spotted was that the dashboard went from proxies: All to proxies: None

**Comment by weihao** [comment]
remove the dashboard and reimport the dashboard

**Comment by DieselGaming** [comment]
I installed the new plugin (2.0.3), deleted the dashboard, re-imported it and its still showing the same thing, do you have anything in mind that I could show you to help?

**Comment by weihao** [comment]
are you using bungeecord? can you show me the cotent of serverIP:port/metrics?

**Comment by weihao** [comment]
> Another thing to note is on the Bukkit version, the Variable is set to use Prometheus, but on this BungeeCord version it is set to Grafana:
> 
> Bukkit:
> <img alt="Screenshot 2021-08-18 at 01 18 42" width="777" src="https://user-images.githubusercontent.com/44411085/129817054-fa9c4a6a-caf2-47e5-9be6-0f89dafb1cd2.png">
> 
> BungeeCord:
> <img alt="Screenshot 2021-08-18 at 01 19 16" width="765" src="https://user-images.githubusercontent.com/44411085/129817107-e49af3d9-273c-468a-a912-2c2d59822b22.png">
> 
> Is this intentional?
> _(I'm completely new to Grafama and set up everything to use this :D)_

I have updated the dashboard to use label_values

**Comment by DieselGaming** [comment]
> are you using bungeecord? can you show me the cotent of serverIP:port/metrics?

https://ptero.co/udazezibew.shell

Even after re-importing the dashboard it shows that value still, but I'll try again.

**Comment by weihao** [comment]
Does Minecraft Prometheus exporter work for you?

**Comment by DieselGaming** [comment]
> Does Minecraft Prometheus exporter work for you?

Yes, the Bukkit/Spigot version works as shown here:
<img width="1221" alt="Screenshot 2021-08-18 at 14 18 47" src="https://user-images.githubusercontent.com/44411085/129905065-f8af07a2-0595-4f7c-92e6-b9528f646f5d.png">

And after deleting and re-importing the BungeeCord on Grafana, it still doesn't appear to work/detect the proxy.

**Comment by weihao** [comment]
can you inspect the grafana dashboard queries?

**Comment by DieselGaming** [comment]
Only get console errors on the BungeeCord dashboard.

Every "refresh" interval this error pops up:
```json
{
    "type": "cancelled",
    "cancelled": true,
    "data": null,
    "status": -1,
    "statusText": "Request was aborted",
    "config": {
        "method": "GET",
        "url": "api/annotations",
        "params": {
            "from": 1629315089936,
            "to": 1629315389936,
            "limit": 100,
            "matchAny": false,
            "dashboardId": 9
        },
        "requestId": "grafana-data-source-annotations-Annotations & Alerts-9",
        "retry": 0,
        "headers": {
            "X-Grafana-Org-Id": 1
        },
        "hideFromInspector": true
    },
    "message": "Query error: -1 Request was aborted"
}
```

Then there is also another WebSocket error which I believe I get on both the Minecraft + BungeeCord pages:
`WebSocket connection to 'ws://serverIP:3000/api/live/ws' failed:`

**Comment by weihao** [comment]
could you get more details? like any error log you could find?

**Comment by DieselGaming** [comment]
Sorry for the incredibly long wait, I suddenly found myself very busy.

Here is my `grafana.log` after loading the dashboard: [https://hastebin.com/lurumewuxi.apache](https://hastebin.com/lurumewuxi.apache)

Where would I find additional logs that may be useful?

**Comment by weihao** [comment]
the request was blocked by CORS.

[see more ](https://community.grafana.com/t/how-to-allow-access-control-allow-origin-for-all-the-apis/2045/8)

**Comment by weihao** [comment]
`/etc/grafana/grafana.ini`
```
domain = <change this to your ip>
```

**Comment by DieselGaming** [comment]
Ok, I moved both Grafana and Prometheus behind my Nginx reverse proxy. After a quick re-configuration of some things, once again the Minecraft version is working fine and detecting my Hub server, but the BungeeCord one remains to provide placeholder information.

I've also added the
`add_header 'Access-Control-Allow-Origin' "*";`
To the Grafana nginx config, and the `Request Origin is not authorized` is still appearing.

I am really stuck now as to why this is happening, and I am very sorry for not being the best help.
Many thanks, however - I hope to eventually resolve this.

**Comment by weihao** [comment]
I have run into this issue, and my solution is

Nginx
```
add_header "Access-Control-Allow-Origin" "*";
            add_header "Access-Control-Allow-Credentials" "true";
            add_header "Access-Control-Allow-Methods" "GET,HEAD,OPTIONS,POST,PUT";
            add_header "Access-Control-Allow-Headers" "Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers";
```

grafana.ini
```
[live]
# allowed_origins is a comma-separated list of origins that can establish connection with Grafana Live.
# If not set then origin will be matched over root_url. Supports wildcard symbol "*".
allowed_origins = <your domain here or *>
```

**Comment by DieselGaming** [comment]
Hi, after adding the missing Nginx headers I no longer get any errors. But placeholder information is still shown. I believe the dashboard doesn't actually detect anything from the Prometheus. Going into the variables settings shows a variable that I think is broken which is why the dashboard isn't showing the data.

**Comment by weihao** [comment]
could you show me what your variables look like?

**Comment by DieselGaming** [comment]
Sorry for the long response I completely forgot to respond and thought I did.

Heres the variables for the bungeecord:

<img width="1280" alt="Screenshot 2021-12-16 at 01 55 55" src="https://user-images.githubusercontent.com/44411085/146293737-396545f0-423b-441a-ac29-5f5efab17b1d.png">

**Comment by DieselGaming** [comment]
And for reference, here is the bukkit one. From what I can see its using Prometheus and detecting the "Hub" correctly.

<img width="1280" alt="Screenshot 2021-12-16 at 01 57 44" src="https://user-images.githubusercontent.com/44411085/146293923-c1979a38-ac0d-4aa0-a888-0ab15dccf2ba.png">

**Comment by weihao** [comment]
Might be related to https://github.com/weihao/bungeecord-prometheus-exporter/issues/88

The data source error should be resolved now
