### ISSUE TITLE
Hourly & Daily Stats Issue

### ISSUE THREAD

**Issue by ImMaxUK** [weihao/bungeecord-prometheus-exporter#30]
Hi there.

I recently installed this plugin on my Flamecord Server.
Upon setting up the dashboard I noticed that hourly and daily statistic boards aren't showing the correct data.
![image](https://user-images.githubusercontent.com/70581172/142278639-c3bba27c-0187-451f-9056-90ac5e718a13.png)

Could this be to-do with the events being different on Flamecord?

**Comment by weihao** [comment]
what is the expected data?

the stats in the picture mean you don't have player logins and therefore this is no disconnects.

**Comment by ImMaxUK** [comment]
> what is the expected data?
> 
> the stats in the picture mean you don't have player logins and therefore this is no disconnects.

Apologies for the late reply.
Shouldn't the List Pings and Connects be different?

**Comment by weihao** [comment]
```
public class ClientConnectEvent
extends Event
implements Cancellable
Event called to represent an initial client connection.
Note: This event is called at an early stage of every connection, handling should be fast.
```

Server List Ping -> Client Connect-> Pre-logins -> Mojang Authentication -> Post-logins -> Disconnects

**Comment by weihao** [comment]
I should probably rename them to avoid any confusion.

**Comment by weihao** [comment]
updated the stats
