### ISSUE TITLE
Help on setting up

### ISSUE THREAD

**Issue by Dacaly** [weihao/bungeecord-prometheus-exporter#34]
Hello there, so I was wondering if I can setup the metrics on my server (which is hosted somewhere and limited to ports and server files), and setup the dashboard on a vos.

**Comment by weihao** [comment]
what is a vos? do you mean vps?

if you can open the ports, you can install the plugin on your server.

and depends on the setup, you can deploy a prometheus and grafana instances on the same host or different host

**Comment by weihao** [comment]
Closing due to no response from reporter
