### ISSUE TITLE
RedisBungee: Switch to LimeWork RedisBungee fork

### ISSUE THREAD

**Issue by galexrt** [weihao/bungeecord-prometheus-exporter#5]
Hey, I just saw the introduction for Redis Bungeesupport.

Would it be possible to use [Limework's](https://github.com/Limework/RedisBungee) fork instead of the [unmaintained](https://www.spigotmc.org/resources/redisbungee.13494/) RedisBungee library?

**Comment by weihao** [comment]
Merged in my changes for RedisBungee to Limework's fork of RedisBungee.

Also updated this repo's dependency to Limework's RedisBungee.
