### ISSUE TITLE
`bungeecord_online_players` gauge metrics accumulate to unusually high values

### ISSUE THREAD

**Issue by kory33** [weihao/bungeecord-prometheus-exporter#61]
We are seeing that `bungeecord_online_players` on a single server steadily rising up to ~700 even if we have only a few people in the said server.

![image](https://user-images.githubusercontent.com/6561358/172060172-0c60e950-e093-421e-be84-6b7d53a9ed34.png)

## Setup information

We are running two separate BungeeCord networks with 2 BungeeCord instances (connected by a RedisBungee) for each. In the network that we observed the issue, we have a `lobby` server that players entering the server first land on the `lobby` and then proceed to game servers (named `s1`, `s2`, ...). For plugin config, [we are using](https://github.com/GiganticMinecraft/seichi_infra/blob/7a89624763eab97788abeff83dda2dc7a8a9b849/seichi-onp-k8s/manifests/seichi-kubernetes/kustomize-bases/minecraft-gateway-bungeecord/configs/plugin-configs.yaml#L7-L23) the default config with `host` changed to `0.0.0.0`.

## Additional information

I can confirm that this is not a Prometheus or Dashboard problem, since `curl`ing `host:9225/metrics` returned data containing incorrect counts:

<details>
<summary>Raw curl result</summary>

```
# HELP bungeecord_server_list_pings_total the number of server list pings in BungeeCord
# TYPE bungeecord_server_list_pings_total counter
bungeecord_server_list_pings_total 12857.0
# HELP bungeecord_redis_player_disconnects_total the number of players disconnects in redisbungee
# TYPE bungeecord_redis_player_disconnects_total counter
bungeecord_redis_player_disconnects_total 0.0
# HELP bungeecord_online_players the number of online players in BungeeCord
# TYPE bungeecord_online_players gauge
bungeecord_online_players{server="s5",} 53.0
bungeecord_online_players{server="s7",} 76.0
bungeecord_online_players{server="kagawa",} 0.0
bungeecord_online_players{server="h1",} 0.0
bungeecord_online_players{server="spade",} 0.0
bungeecord_online_players{server="lobby",} 749.0
bungeecord_online_players{server="eve",} 0.0
bungeecord_online_players{server="cre",} 0.0
bungeecord_online_players{server="petra",} 0.0
bungeecord_online_players{server="reset",} 0.0
bungeecord_online_players{server="s1",} 122.0
bungeecord_online_players{server="s2",} 56.0
bungeecord_online_players{server="s3",} 69.0
# HELP bungeecord_redis_bungee_online_proxies the number of online redisbungee proxy
# TYPE bungeecord_redis_bungee_online_proxies gauge
bungeecord_redis_bungee_online_proxies 0.0
# HELP bungeecord_managed_servers the number of managed servers in BungeeCord
# TYPE bungeecord_managed_servers gauge
bungeecord_managed_servers 13.0
# HELP bungeecord_redis_online_players the number of online redisbungee players
# TYPE bungeecord_redis_online_players gauge
# HELP bungeecord_player_connects_total the number of player logins in BungeeCord
# TYPE bungeecord_player_connects_total counter
bungeecord_player_connects_total 1127.0
# HELP bungeecord_redis_player_connects_total the number of players joined in redisbungee
# TYPE bungeecord_redis_player_connects_total counter
bungeecord_redis_player_connects_total 0.0
# HELP bungeecord_jvm_threads_current Current thread count of a JVM
# TYPE bungeecord_jvm_threads_current gauge
bungeecord_jvm_threads_current 59.0
# HELP bungeecord_jvm_threads_daemon Daemon thread count of a JVM
# TYPE bungeecord_jvm_threads_daemon gauge
bungeecord_jvm_threads_daemon 16.0
# HELP bungeecord_jvm_threads_peak Peak thread count of a JVM
# TYPE bungeecord_jvm_threads_peak gauge
bungeecord_jvm_threads_peak 73.0
# HELP bungeecord_jvm_threads_started_total Started thread count of a JVM
# TYPE bungeecord_jvm_threads_started_total counter
bungeecord_jvm_threads_started_total 6549.0
# HELP bungeecord_jvm_threads_deadlocked Cycles of JVM-threads that are in deadlock waiting to acquire object monitors or ownable synchronizers
# TYPE bungeecord_jvm_threads_deadlocked gauge
bungeecord_jvm_threads_deadlocked 0.0
# HELP bungeecord_jvm_threads_deadlocked_monitor Cycles of JVM-threads that are in deadlock waiting to acquire object monitors
# TYPE bungeecord_jvm_threads_deadlocked_monitor gauge
bungeecord_jvm_threads_deadlocked_monitor 0.0
# HELP bungeecord_jvm_threads_state Current count of threads by state
# TYPE bungeecord_jvm_threads_state gauge
bungeecord_jvm_threads_state{state="WAITING",} 20.0
bungeecord_jvm_threads_state{state="TERMINATED",} 0.0
bungeecord_jvm_threads_state{state="TIMED_WAITING",} 26.0
bungeecord_jvm_threads_state{state="BLOCKED",} 0.0
bungeecord_jvm_threads_state{state="RUNNABLE",} 13.0
bungeecord_jvm_threads_state{state="NEW",} 0.0
# HELP bungeecord_jvm_memory JVM memory usage
# TYPE bungeecord_jvm_memory gauge
bungeecord_jvm_memory{type="max",} 1.037959168E9
bungeecord_jvm_memory{type="used",} 2.51358936E8
bungeecord_jvm_memory{type="free",} 7.86600232E8
bungeecord_jvm_memory{type="allocated",} 1.037959168E9
# HELP bungeecord_player_disconnects_total the number of player disconnects in BungeeCord
# TYPE bungeecord_player_disconnects_total counter
bungeecord_player_disconnects_total 1085.0
# HELP bungeecord_jvm_gc_collection_seconds Time spent in a given JVM garbage collector in seconds.
# TYPE bungeecord_jvm_gc_collection_seconds summary
bungeecord_jvm_gc_collection_seconds_count{gc="Copy",} 157.0
bungeecord_jvm_gc_collection_seconds_sum{gc="Copy",} 1.274
bungeecord_jvm_gc_collection_seconds_count{gc="MarkSweepCompact",} 3.0
bungeecord_jvm_gc_collection_seconds_sum{gc="MarkSweepCompact",} 0.129
# HELP bungeecord_player_connects_created the number of player logins in BungeeCord
# TYPE bungeecord_player_connects_created gauge
bungeecord_player_connects_created 1.654299670094E9
# HELP bungeecord_player_disconnects_created the number of player disconnects in BungeeCord
# TYPE bungeecord_player_disconnects_created gauge
bungeecord_player_disconnects_created 1.654299670096E9
# HELP bungeecord_redis_player_connects_created the number of players joined in redisbungee
# TYPE bungeecord_redis_player_connects_created gauge
bungeecord_redis_player_connects_created 1.654299670102E9
# HELP bungeecord_redis_player_disconnects_created the number of players disconnects in redisbungee
# TYPE bungeecord_redis_player_disconnects_created gauge
bungeecord_redis_player_disconnects_created 1.654299670102E9
# HELP bungeecord_server_list_pings_created the number of server list pings in BungeeCord
# TYPE bungeecord_server_list_pings_created gauge
bungeecord_server_list_pings_created 1.654299670097E9
```

</details>

---

Do you think it is possible that `ServerInfo#getPlayers` in this line is returning obsolete player connections too?

https://github.com/weihao/bungeecord-prometheus-exporter/blob/45423eef6b7e3921352676936cd7ca722b0738f8/src/main/java/org/akadia/prometheus/bungeecord/metrics/OnlinePlayers.java#L19

**Comment by weihao** [comment]
Could you confirm you are using the latest bungeecord / waterfall? what version is it? I can't seem to reproduce it.

**Comment by kory33** [comment]
> Could you confirm you are using the latest bungeecord / waterfall? what version is it? I can't seem to reproduce it.

We are using `itzg/bungeecord:java17-2022.1.0` for the BungeeCord deployment with `TYPE=WATERFALL`, and the container log says that the waterfall version is `1.18-488`, which is the [current latest](https://papermc.io/downloads#Waterfall).

```
2022-06-06 04:33:58	
[init] Resolving type given WATERFALL
2022-06-06 04:34:12	
[init] Downloading https://papermc.io/api/v2/projects/waterfall/versions/1.18/builds/488/downloads/waterfall-1.18-488.jar
2022-06-06 04:34:14	
[mc-image-helper] 19:34:14.759 INFO  : Downloaded /server/waterfall-1.18-488.jar
```

We publish the whole setup ([base](https://github.com/GiganticMinecraft/seichi_infra/tree/7a89624763eab97788abeff83dda2dc7a8a9b849/seichi-onp-k8s/manifests/seichi-kubernetes/kustomize-bases/minecraft-gateway-bungeecord) and [overlay](https://github.com/GiganticMinecraft/seichi_infra/tree/7a89624763eab97788abeff83dda2dc7a8a9b849/seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-gateway/bungeecord)), but if you still can't reproduce the issue, I could try minimizing to a minimal self-contained setup.

**Comment by weihao** [comment]
investigating.

one thing I noticed is why did you turn off ping_passthrough?
https://github.com/GiganticMinecraft/seichi_infra/blob/7a89624763eab97788abeff83dda2dc7a8a9b849/seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-gateway/bungeecord/bungeecord-config-patch.yaml#L76

**Comment by weihao** [comment]
i can't get your setup up.

https://github.com/GiganticMinecraft/seichi_infra/blob/7a89624763eab97788abeff83dda2dc7a8a9b849/seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-gateway/bungeecord/bungeecord-plugin-configs-patch.yaml#L31-L32

i can't find redis deployment

**Comment by inductor** [comment]
@weihao currently we still use on-prem vm redis and we are planning to migrate it to containers. 
Ref. https://github.com/GiganticMinecraft/seichi_infra/pull/462

**Comment by weihao** [comment]
i just published a minimal and self-contained setup: https://github.com/weihao/docker-minecraft-network

and I can't reproduce the error, let me know if you catch something

**Comment by kory33** [comment]
> investigating.
> 
> one thing I noticed is why did you turn off ping_passthrough? https://github.com/GiganticMinecraft/seichi_infra/blob/7a89624763eab97788abeff83dda2dc7a8a9b849/seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-gateway/bungeecord/bungeecord-config-patch.yaml#L76

@weihao [This is the default setting of BungeeCord](https://www.spigotmc.org/wiki/bungeecord-configuration-guide/). Anyways ping value (whether ping packet is passed through or not) difference is insignificant, RedisBungee is responsible for displaying the player count, and a MotD plugin is controlling motd so I didn't feel obliged to turn this on.

> @weihao currently we still use on-prem vm redis and we are planning to migrate it to containers. Ref. [GiganticMinecraft/seichi_infra#462](https://github.com/GiganticMinecraft/seichi_infra/pull/462)

Regarding this setup, one mistake we have made is that we have unintentionally shared the single redis instance across two disjoint BungeeCord networks. However I don't see a reason why that could be causing the issue.

@weihao Thank you so much for the minimal self-contained setup! Once I have some more time this weekend I will setup a self-contained reproduction, and see what could be causing the issue.

**Comment by weihao** [comment]
Might be related to https://github.com/weihao/bungeecord-prometheus-exporter/issues/88

The data source error should be resolved now
