### ISSUE TITLE
No data in dashboard

### ISSUE THREAD

**Issue by Tom18314** [weihao/bungeecord-prometheus-exporter#77]
Every time I refresh the dashboard the data is different and incorrect. I imported the latest version of the dashboard
![image](https://user-images.githubusercontent.com/72739475/198851821-da5dde68-dcb8-4d00-99cb-6c479122ac52.png)

Prometheus is working:
![image](https://user-images.githubusercontent.com/72739475/198851834-a0ade46c-ba00-4c41-a9ea-a3287846f057.png)

And the correct datasource is added:
![image](https://user-images.githubusercontent.com/72739475/198851852-6fc052c4-04c7-4f71-a9f5-b3e9ec78ea15.png)

I also have the latest version of the plugin enabled:
![image](https://user-images.githubusercontent.com/72739475/198851865-0e28df50-d594-4373-ab3a-4e4aec6e0d67.png)

**Comment by weihao** [comment]
The dashboard naming is weird when you imported.

Could you paste the metrics from the exporter?

Also what is your grafana version?

**Comment by Tom18314** [comment]
**Grafana version: v9.1.6 (92461d8d1e)** 

**Metrics:**
[metrics.txt](https://github.com/weihao/bungeecord-prometheus-exporter/files/9944080/metrics.txt)

**Comment by weihao** [comment]
try grafana 9.2.3 and let me know

**Comment by weihao** [comment]
Might be related to https://github.com/weihao/bungeecord-prometheus-exporter/issues/88

The data source error should be resolved now
