### ISSUE TITLE
Very unclear what to do- Using vps

### ISSUE THREAD

**Issue by Zeanox** [weihao/bungeecord-prometheus-exporter#79]
Hello! I was watching the tutorial and it is just not suited for if you are using a vps with docker. ip is 0.0.0.0 but i can not access the data because there is no way to smh. Then with this scrape and job thing i just cant get it?

**Comment by weihao** [comment]
Could you describe your setup and I will help you.

Are you running a minecraft server in a docker container?

- If you ping localhost inside of the container, can you get data?
- If you publish the port 9225 from the container to your host, can you access the data?

**Comment by weihao** [comment]
stale
