### ISSUE TITLE
Importing dashboard goes wrong?

### ISSUE THREAD

**Issue by Tom974** [weihao/bungeecord-prometheus-exporter#88]
Hey, every time i try to import the dashboard in grafana, i get this following error:

![image](https://user-images.githubusercontent.com/55812394/213926697-5696c6bd-b58c-4d6c-9074-57030b499dc3.png)

Do you guys know what this is and how i can fix it?

**Comment by weihao** [comment]
what is your grafana version?

**Comment by StealWonders** [comment]
Hello. I am using bungeecord-prometheus-exporter for the first time using Grafana `v9.3.6 (978237e7cb)`. I get the same error. Is there any further information I can provide you with?

**Comment by weihao** [comment]
thanks, @StealWonders, it seems like a common error.

have you already added a prometheus data source in grafana?

**Comment by weihao** [comment]
updated the dashboard, please try again
